---
pagetitle: "CStories.app - Home"
listing:
  - id: list-workshops
    contents:
      - "workshops/*.qmd"
    type: table
    sort-ui: false
    filter-ui: false
    field-types:
      workshop-date: date
      num: number
    fields: [workshop-date, title, workshop-host, image]
    #field-required: [num, title, date]
    date-format: "medium"
    sort: "workshop-date"
    field-display-names:
      workshop-date: "Date"
      workshop-host: "Host"
  - id: list-apps
    contents:
      - "apps/*.qmd"
    type: grid
    field-display-names:
      title: "App"
    # categories: true
---

***Empowering Communities with Easy-to-Use Digital Tools to Participate in Marine Renewable Energy Planning & Development***

## Workshops

This Phase 1 project is active June, 2022 to March, 2023. We will conduct a series of workshops in California to solicit feedback for building out a prototype tool and solicit for Phase 2 to follow.

::: {#list-workshops}
:::

::: screen-inset-shaded
### Quick Links

for Workshop at Santa Barbara Maritime Museum (Sep 21, 2022):

-   **Slides**:\
    [CStories_SBMM.pdf](./files/CStories_SBMM.pdf)

-   **Poll**:\
    [pollev.com/rupertsmudge433](https://pollev.com/rupertsmudge433)

-   **Video**:\
    [BOEM Renewable Energy Whiteboard - YouTube](https://www.youtube.com/watch?v=GEAiyd4Yi5M&t=195s)

-   **Input Tools**

    -   Portals

        -   [caoffshorewind.databasin.org](https://caoffshorewind.databasin.org)

        -   [marinecadastre.gov/oceanreports](https://marinecadastre.gov/oceanreports)

    -   Infographic

        -   [sanctuarywatch.ioos.us/webcr-channelislands](https://sanctuarywatch.ioos.us/webcr-channelislands/)

-   **Output Tools**

    -   Infographic

        -   [sanctuarywatch.ioos.us/webcr-channelislands](https://sanctuarywatch.ioos.us/webcr-channelislands/)

    -   Weighted Map\
        [ecoquants.shinyapps.io/nrel-uses](https://ecoquants.shinyapps.io/nrel-uses)

    -   Tradeoff App\
        [shiny.marinebon.app/siting](https://shiny.marinebon.app/siting)

-   **Feedback**\
    [forms.gle/Sf1QAnAaUBPyaZZBA](https://forms.gle/Sf1QAnAaUBPyaZZBA)
:::

## Applications

Here are a few existing applications from other  projects that we developed with functionality from which we'll ask for feedback based on what ***does*** and ***does [not]{.underline}*** work for development of a new application oriented around informing and empowering community voices.

::: {#list-apps}
:::


## Contact

- Grace Chang ([gchang@integral-corp.com](gchang@integral-corp.com); 831-576-2881)

- Ben Best ([ben@ecoquants.com](mailto:ben@ecoquants.com); 805-705-9770)
